FROM node:lts-bullseye

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq chromium=99.0.4844.74-1~deb11u1 && \
  mkdir -p ~/osnap_chromium_961656/chrome-linux && \
  mv /usr/lib/chromium/* ~/osnap_chromium_961656/chrome-linux && \
  mv ~/osnap_chromium_961656/chrome-linux/chromium ~/osnap_chromium_961656/chrome-linux/chrome && \
  rm -f /usr/bin/chromium

COPY _build /usr/local
