name: Publish packages to npm

on:
  release:
    types: [prereleased, released]

jobs:
  build-platform:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      # Setup node to install esy
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # Install esy globally
      - name: Install esy
        run: |
          npm install -g esy
      # Checkout the projects sources
      - uses: actions/checkout@v2
      # Add an esyrc to set the cache path for esy.
      # We do this because of this issue with esy: https://github.com/esy/esy/issues/1083
      - name: Add esyrc
        run: |
          echo '{ "prefixPath": ".esy" }' > .esyrc
      - uses: esy/github-action@master
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}
          esy-prefix: .esy
      # Create the NPM package for this platform
      - name: Create npm package
        run: esy release
      # Upload the npm package as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: _release/

  prepare-publish:
    name: Prepare publish to npm
    needs: build-platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
          submodules: true
      # Download platform artifacts
      - name: Download Linux release
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-latest
          path: ubuntu-latest
      - name: Download Windows release
        uses: actions/download-artifact@v2
        with:
          name: windows-latest
          path: windows-latest
      - name: Download macOS release
        uses: actions/download-artifact@v2
        with:
          name: macOS-latest
          path: macOS-latest
      # Move artifacts in place
      - name: Move artifacts
        run: |
          mkdir -p _release/platform-linux
          mkdir -p _release/platform-windows-x64
          mkdir -p _release/platform-darwin
          cp -a ubuntu-latest/. _release/platform-linux
          cp -a windows-latest/. _release/platform-windows-x64
          cp -a macOS-latest/. _release/platform-darwin
      - name: Prepare package
        run: node .github/workflows/bundle-release.js
      # Create a npm package that can easily be published and tested
      - name: npm pack
        run: npm pack .
        working-directory: _release
      - name: move package
        run: mv _release/*.tgz osnap.tgz
      # Upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: _release/
      - uses: actions/upload-artifact@v2
        with:
          name: release-tarball
          path: osnap.tgz

  test-platform:
    name: Test installing ${{ matrix.os }}
    needs: prepare-publish
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Download ${{ matrix.os }} release
        uses: actions/download-artifact@v2
        with:
          name: release-tarball
      - name: test install
        run: npm -g install ./osnap.tgz
      - name: test binary
        run: npx osnap --help=plain

  publish:
    runs-on: ubuntu-latest
    needs: [prepare-publish, test-platform]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: npm publish prerelease
        if: ${{ github.event.release.prerelease }}
        run: npm publish ./osnap.tgz --tag=next --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: npm publish
        if: ${{ !github.event.release.prerelease }}
        run: npm publish ./osnap.tgz --tag=latest --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
